name: Github Actions로 테스트 자동화하기

# 언제 실행할거야?
on: workflow_dispatch

# 어떤 직업
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: 첫 번째 작업의 1단계
        run: echo "첫 번째 작업의 1단계입니다."
      - name: 첫 번째 작업의 2단계
        run: echo "첫 번째 작업의 2단계입니다."

  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: 두 번째 작업의 1단계
        run: echo "두 번째 작업의 1단계입니다."
      - name: 두 번째 작업의 2단계
        run: echo "두 번째 작업의 2단계입니다."
